"""Draft domain context from catalog metadata.

This is a light version of Anthropic's data-context-extractor idea, adapted for
data-agent. It does not mutate references automatically; it creates reviewable
Markdown and eval-case drafts so humans can confirm domain meaning before rules
become authoritative.
"""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog.json"


def load_catalog(path=CATALOG):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _iter_tables(catalog):
    for schema, tables in catalog.get("schemas", {}).items():
        for table, info in tables.items():
            yield schema, table, info


def select_tables(catalog, patterns):
    compiled = [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    selected = []
    for schema, table, info in _iter_tables(catalog):
        fq = f"{schema}.{table}"
        haystack = " ".join([fq, json.dumps(info, ensure_ascii=False)])
        if any(pattern.search(haystack) for pattern in compiled):
            selected.append((schema, table, info))
    return selected


def summarize_table(schema, table, info):
    cols = info.get("columns", [])
    key_cols = [c["name"] for c in cols if c.get("key")]
    date_col = info.get("date_col")
    unit = info.get("unit")
    dimensions = info.get("dimensions", {})
    return {
        "fq": f"{schema}.{table}",
        "type": info.get("type"),
        "row_count": info.get("row_count", 0),
        "coverage": info.get("coverage"),
        "flags": info.get("flags", []),
        "date_col": date_col,
        "date_range": [info.get("date_min"), info.get("date_max")] if date_col else [],
        "unit": unit,
        "dimensions": dimensions,
        "primary_key": key_cols or info.get("primary_key", []),
        "columns": [c["name"] for c in cols[:16]],
    }


def build_reference_markdown(domain, selected):
    lines = [
        f"# {domain} Domain Draft",
        "",
        "Generated by `tools/context_extractor.py`. Review before moving content into a formal reference file.",
        "",
        "## Scope",
        "",
        "Selected tables based on catalog patterns. Fill in business definitions, metric formulas, and standard filters.",
        "",
        "## Quick Table Map",
        "",
        "| Table | Rows | Coverage | Flags | Date | Unit | Dimensions |",
        "|-------|------|----------|-------|------|------|------------|",
    ]
    summaries = [summarize_table(*item) for item in selected]
    for item in summaries:
        flags = ", ".join(item["flags"]) or "-"
        date_range = " - ".join([v for v in item["date_range"] if v]) or "-"
        dims = ", ".join(f"{k}={v}" for k, v in item["dimensions"].items()) or "-"
        unit = item["unit"] or "-"
        lines.append(
            f"| `{item['fq']}` | {item['row_count']} | {item['coverage']} | {flags} | {date_range} | {unit} | {dims} |"
        )

    lines.extend(["", "## Table Notes", ""])
    for item in summaries:
        lines.extend([
            f"### `{item['fq']}`",
            f"- Type: {item['type']}",
            f"- Primary key/catalog key: {', '.join(item['primary_key']) or 'not declared'}",
            f"- Important columns: {', '.join(item['columns'])}",
            "- Business meaning: TODO",
            "- Standard filters: TODO",
            "- Common gotchas: TODO",
            "- Sample query: TODO",
            "",
        ])

    lines.extend([
        "## Metrics To Confirm",
        "",
        "| Metric | Formula | Source | Caveats |",
        "|--------|---------|--------|---------|",
        "| TODO | TODO | TODO | TODO |",
        "",
        "## Questions For Analyst",
        "",
        "1. Which of these tables are authoritative for this domain?",
        "2. What rows should always be excluded, if any?",
        "3. Which metrics have exact business formulas?",
        "4. What mistakes do new analysts usually make with these tables?",
        "",
    ])
    return "\n".join(lines)


def build_eval_drafts(domain, selected):
    drafts = []
    for schema, table, info in selected:
        fq = f"{schema}.{table}"
        coverage = info.get("coverage")
        flags = info.get("flags", [])
        if coverage == "SINGLE_STOCK":
            drafts.append({
                "id": f"block_{table}_cross_section_claim",
                "intent": f"{domain}: 用 {table} 做全市场排名或占比",
                "sql": f"SELECT * FROM {fq} LIMIT 20",
                "expected_risk": "single_stock_misuse",
                "notes": "Turn into executable eval after deciding the risky query shape.",
            })
        if coverage == "TINY":
            drafts.append({
                "id": f"warn_{table}_tiny_sample",
                "intent": f"{domain}: 用 {table} 概括整体趋势",
                "sql": f"SELECT * FROM {fq} LIMIT 20",
                "expected_risk": "tiny_source",
                "notes": "Should disclose row count/date range if used.",
            })
        if "SHORT_HISTORY" in flags:
            drafts.append({
                "id": f"block_{table}_trend_short_history",
                "intent": f"{domain}: 用 {table} 做过去一段时间趋势",
                "sql": f"SELECT * FROM {fq} LIMIT 20",
                "expected_risk": "short_history_trend",
                "notes": "Replace SQL with a date-grouped query for executable eval.",
            })
    return drafts


def build_context_draft(domain, patterns, catalog_path=CATALOG):
    catalog = load_catalog(catalog_path)
    selected = select_tables(catalog, patterns)
    return {
        "domain": domain,
        "patterns": patterns,
        "table_count": len(selected),
        "reference_markdown": build_reference_markdown(domain, selected),
        "eval_drafts": build_eval_drafts(domain, selected),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", required=True)
    ap.add_argument("--pattern", action="append", required=True, help="regex over table/catalog text")
    ap.add_argument("--out-dir", default=None)
    args = ap.parse_args()

    draft = build_context_draft(args.domain, args.pattern)
    if args.out_dir:
        out_dir = Path(args.out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        slug = re.sub(r"[^A-Za-z0-9_-]+", "_", args.domain).strip("_").lower()
        md_path = out_dir / f"{slug}.md"
        eval_path = out_dir / f"{slug}_eval_drafts.json"
        md_path.write_text(draft["reference_markdown"], encoding="utf-8")
        eval_path.write_text(json.dumps(draft["eval_drafts"], ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps({"reference": str(md_path), "eval_drafts": str(eval_path)}, ensure_ascii=False))
    else:
        print(json.dumps(draft, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
